language: java
jdk: oraclejdk8
sudo: false
env:
  global:
    # GITHUB_TOKEN
    - secure: "lYkrL/XJvXIiVWnBAnjhh9jnJ7Y0Vxjye/4pQHzZwLg8+y4RNPYuThE0jexpMzBSpsHN1duN6Y7KVi30Lu2KlbtCKj9rAfjdN8/VH15TCA6LfunW1ru4jiFUa204AtC36JS9q+XOFSa2fINkLVvpRwuLlOoSDxdvETq9+q5MY5ijlngaEJXHqsLih5s3B3mwyh5OKzKhx3ZeP0KwQl91tT7jH/tj/H+cuv9vQwK4qPrsBa7nwOu+muclJQc0NbYPLeGOOFv6bkXYWty95rLNaD7p2/+OFqKzdCrDRpyTzJpfdUEd0CHJgTMYTTO76vhW+nSoW9+98oU+5TAWhuyEWtOZCK9SY4PJx7M6FsKgp+i4pJgsV7MniCevt1OlmVyrDQoTxZ8D1lVkHd3YLJf70EB9/4I4iJZQpRA0vjImcacO3dcpvQaJwUKCCE59yFoCsObv7Esn2qNKn+9IEfGRH1t1DZggOdwVs94MnsJgu2OdIHfHLf4WbT72b97BsUkAWFtE1sUm0SKuQLpzyOcr8AjEHU6XNpP4wvP585pjDO+72UQ8J/JC4GZuXCLyZjCWCYc0fFfBbL6z9Nk2arKr3G2uX5RQUDhi2ygtCO+nkHITeV9E6kto2MEpVO62DcIMvGL0Z07/5O8GxaHFgI1hk+HSkC+XeeWVxE6ias+DUCA="
    # SONAR_LOGIN
    - secure: "KzKBYGIHFQZgXsF+Hi5BBJXg1Kt5wNNo8lex0gzIL0P5CP8BNCwgxAXDJxqK90cliyzbMXmOMgkFCQvP7T+w8b6WT8MX5siyFhBzIh4jq4kSVEFhONKd0nbwyO0anqUbpoWwRsEaSkDw0HRiGuENq1zxmk9ayusVDp9SoywFMnnbor3XkjPS6Y3aDYjUxPMWE/PZMSdnJWCY/dAj68/Uy+EXF59BEKemmTq1BI8tJnepQb0eF/01omCEjFpDxHrh9/rRRlppSrnvx/Xe+DfbwSFvgr0tgMVxnSGoTE2APcw77NSrdSNEe2XhzHXQalkDjbE5whsHX+Qn0Ujz0C06d7Q2ywXsIxZFWqymUoZ3XwarDrxEt5oWuUyQUu5d/+vXf8BKTcjTfklGOlrOHrxc12HYc7yjFAqwlCLUcNNu4w9Yaac8c/3730kVk2R9i9FmlysWRupiMiYooxS+VYvMvN9xv0A+RR7Gl4Fz1uWFdyDWPQ5eaU6tEmoKhsBuRDa1j5VOQ4/wL2TxsyRIN/C/soZLVBEs6oaG7EGBBezKlfCH78RUpzvSrR7iwT/EiIgSX8/yghcjy4MtPhUZMK6f+6Yf9spCzD9yGg/JCd8leQCal8EmG6qMJYtJXSFq914t+ZYtj83FW7zt+p+nJqTsQKs3gXvPTgtP9EJshkaqfC8="
before_cache:
  - rm -rf target/dictionary/*.zip
cache:
  directories:
    - target/dictionary
# Currently git-lfs has trouble, so skip downloading csv file from LFS.
git:
  lfs_skip_smudge: true
# Currently `mvn package` cannot work due to git-lfs problem, see issue #1.
# So we need to skip invoking `mvn install` for now.
# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true
script:
  - mvn jacoco:prepare-agent test -B
after_success:
  - mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN
