language: java
jdk: oraclejdk8
dist: trusty
before_install:
  # Decrypt settings.xml and codesigning.asc which is necessary to deploy to Sonatype Maven Repositories
  - if [ -n "$encrypted_a8b7489a9830_key" ]; then openssl aes-256-cbc -K $encrypted_a8b7489a9830_key -iv $encrypted_a8b7489a9830_iv -in .travis/settings_codesigning.tar.enc -out .travis/settings_codesigning.tar -d; tar xf .travis/settings_codesigning.tar -C .travis; fi
  - if [ -f .travis/codesigning.asc ]; then gpg --fast-import .travis/codesigning.asc; fi
install: true
addons:
  sonarcloud:
    organization: "worksapplications"
    token:
      secure: "0OSnmNTuPizTDRI0ygBXEyI2cnCVJJKxNnRRixxjBpW60OrqwPmD6imnwaViIsgnG3jl68pMmLKybU+MDq90QHQFvlmViD3lt5zMUBiG0Hmjgsyo/+L3Q3xXyucEEojluxi6WEh9AeMYRTX/p4iiwd8R41V0Y7hpMkFvG5+ZlaU8wlnvW/qTZCW+j9i1//Z6zLpszNM+FmawDSWTsK2MiGCABhI1UrX1UG6Mrox32fVZo86pwTOLfYJE3ZS/O7+erupTRhmkQO++xPMm7yLJuzyPqWriGukIZJUKMhxN/4iKuQSec16C3P0hi/3uMoV3x3NS+yf5hAJFzcT3t1d1NN2akvUALTLL7MRjGc7kpivO6a1AS1HsmSCbRtHBu/4QLknMeaYS8WJuQLHk6ZidIGkB5p8eID2+nX3zbd+cNj84wNbqLNRf833AvwCJIzkYVgUbSomOHTT7NLIAlOKF3zTa8h6T44M1cLjQY3GZkG6nS0XUkznekTOQBdwFBSAPS3bEgSBOtDKczA7KrTOAJe3FdUQ2PooL4qLQZnzealGb/e1k97BiLIQ8QkDhYG6ei69lnuJ8Dxj0Kxxm5qJj0JpKd3aXSuOcC16fDuCW5phjO7s0I9ZYWxCGYtakTVZvcEkDnEh3HHeHmmh2D7MSN9Mv0OJn1/ALLEROzff8sgg="
script:
  - mvn jacoco:prepare-agent test -B
after_success:
  - mvn sonar:sonar -Dsonar.login=$SONAR_LOGIN
deploy:
  - provider: script
    script: mvn clean deploy -P release -B --settings .travis/settings.xml
    # Skip cleanup to keep decrepted .travis/settings.xml in workspace
    # https://docs.travis-ci.com/user/deployment/
    skip_cleanup: true
    on:
      branch: develop
cache:
  directories:
    - $HOME/.m2/repository/
